web-app/main/__init__.py
# For relative imports to work in Python 3.6
import os, sys; sys.path.append(os.path.dirname(os.path.realpath(__file__)))

from flask import Flask
from .routes import main


def create_app():
    app = Flask(__name__)
    app.register_blueprint(main)
    return app

web-app/main/routes.py
#!/usr/bin/env python3
from flask import request, render_template, Blueprint
import requests
from Metrics import zipcode_metric
from prometheus_client import generate_latest

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template('index.html')

@main.route("/forecast", methods=["POST"])
def forecast():
    if request.method == "POST":
        zipcode = request.form.get("user_zip_code", "")
        minutes = int(request.form.get("minutes", ""))
        seconds = int(request.form.get("seconds", ""))
        pace_in_seconds = minutes * 60 + seconds
        zipcode_metric.labels(zipcode=zipcode).inc()
        params = {
            'zipcode': zipcode,
            'pace': pace_in_seconds
        }
        print(pace_in_seconds)
        forecast = requests.get(f"https://pace-calculator-analyzer.onrender.com/forecast/", params=params, timeout=3)
        print("Get forecast status code: " + str(forecast.status_code))
        return render_template('forecast.html', user_zip_code = zipcode, forecast=forecast.json())
    else:
        return "404 not found"

@main.route("/about")
def about():
    return render_template('about.html')

@main.route("/metrics")
def metrics():
    return generate_latest()

web-app/main/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} About {% endblock %}</h1>
    <p>Runners using a coach or following a specific training plan will receive workouts at a prescribed running pace intended to create physiological adaptation. 
        If the weather is too hot or humid the originally prescribed pace will be too difficult to illicit the desired adaptation or to complete at all. 
        Pace calculator helps runners adjust their running pace to fit the local weather conditions. It uses the National Weather Service's API to retrieve the forecast for the user's zip code. 
        Pace calculator is an academic project meant to demonstrate the use of testing, monitoring, and reporting for a microservice architecture. </p>
{% endblock %}

web-app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %} - Pace Calculator</title>
    <style>
        nav a {
            color: #d64161;
            font-size: 3em;
            margin-left: 50px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index') }}">Home</a>
        <a href="{{ url_for('main.about') }}">About</a>
    </nav>
    <hr>
    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

web-app/main/templates/forecast.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Home {% endblock %}</h1>
    <h1>Welcome!</h1><br>
    <h3>{{ utc_dt }}</h3>
    <h3>Forecast for {{ user_zip_code }}</h3>
    <div style="width: 50%; margin: auto">
        {% for entry in forecast %}
        <div style="padding: 10px; background-color: #EEE; margin: 20px">
            <p style="font-size: 24px">{{ entry.start_time }}</p>
            <p style="font-size: 24px">{{ entry.forecast }}</p>
            <p style="font-size: 24px">Temperature: {{ entry.temperature }}</p>
            <p style="font-size: 24px">Dew Point: {{ entry.dew_point }}</p>
            <p style="font-size: 24px">Suggested Pace: {{ entry.pace }}</p>
        </div>
        {% endfor %}
    </div>

{% endblock %}

web-app/main/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome!</h1><br>
    <p>Enter your running pace and zipcode for an adjusted workout based on local weather conditions</p>
    <form action="/forecast" method="POST">
        <p>
            <input name="user_zip_code">
            <label for="user_zip_code">Zip Code</label><br>
        </p>
        <p>
            <input name="minutes">
            <label for="minutes">Minutes</label><br>
        </p>
        <p>
            <input name="seconds">
            <label for="seconds">Seconds</label><br>
        </p>
        <input type="submit" value="Submit">
    </form>
    <h3>{{ utc_dt }}</h3>
{% endblock %}